kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
  annotations:
    siteURL: "https://www.getsiteinspector.com"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-vol
          persistentVolumeClaim:
            claimName: postgres-vol
      containers:
        - name: postgres
          image: 'postgres:12.2' #change version
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: siteinspector
          resources: #change in for your project
            limits:
              cpu: "1000m"
              memory: 512Mi
            requests:
              cpu: "500m"
              memory: 256Mi
          livenessProbe:
            tcpSocket:
              port: 5432
          readinessProbe:
            tcpSocket:
              port: 5432
          volumeMounts:
            - name: postgres-vol
              mountPath: /var/lib/postgresql/data
          imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 30
