kind: Service
apiVersion: v1
metadata:
  name: postgres
  annotations:
    siteURL: "https://www.getsiteinspector.com"
  labels:
    app: postgres
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
