apiVersion: v1
kind: Service
metadata:
  annotations:
    siteURL: "https://www.getsiteinspector.com"
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
    - name: "808"
      port: 808
      targetPort: 808
  selector:
    io.kompose.service: app
