kind: Service
apiVersion: v1
metadata:
  name: redis
  annotations:
    siteURL: "https://www.getsiteinspector.com"
  labels:
    app: redis
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
